(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'fd3bcada-c82e-4ef8-8446-dece8025006a-bootstrap-container',
          componentName:'Calendar',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"anchorId":"b9wnz","visitorMode":true,"manualEvents":[{"id":"9c50f2be-bb9a-4ba3-a548-7d5383b06d6d","date":"07\u002F07\u002F2020","title":"CLONE SYNTHESIS - DEBUT EP WORLDWIDE RELEASE","desc":"{\"blocks\":[{\"key\":\"2u8ne\",\"text\":\"Clone Synthesis, self-titled debut EP releasing worldwide on 07-07-2020 on all major music streaming platforms.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{\"fontScale\":0}}],\"entityMap\":{}}","start":"12 AM","end":"","location":"All Major Music Streaming Platforms","allDay":false}],"env":"production","icalURL":"https:\u002F\u002Fcalendar.google.com\u002Fcalendar\u002Fical\u002Fwsb.vnext%40gmail.com\u002Fpublic\u002Fbasic.ics","websiteId":"6eec081e-6752-4c51-a666-cd173764586f","accountId":"b4b57967-b985-11ea-820c-3417ebe73f23","pageId":"af872456-783c-43d6-8723-04c7e07ba4b7","id":"fd3bcada-c82e-4ef8-8446-dece8025006a","staticContent":{"moreEvents":"More Events","editNoEvents":"No upcoming events.","publishNoEvents":"Calendar synced! But no event found in current calendar.","eventDetails":"Event Details","allDay":"All day","defaultEvents":{"one":{"title":"Sunday Supper Club","desc":"A culinary event with foods from all over the world. This is a weekly club you can join for a small fee. Learn cooking methods from top chefs.","location":"144 W Elm St, Chicago, IL 60610, USA"},"two":{"title":"Evenings in the Park","desc":"We invite you to listen to live bands play beautiful music in the park. Enjoy the sounds of Laureen Davis and the Kings, and enjoy wine tastings hosted by 5th Ave Wines and Spirits.","location":"Estuary Park"},"three":{"title":"Morning Brews & Views","desc":"Enjoy free samples of our latest brews while overlooking the beautiful sites of our city. Plenty of iced and hot teas, plus gourmet coffee drinks to perk up your day. Complimentary biscuits for everyone!","location":"The Teapot and Brew Club"},"four":{"title":"Super Saturday Sale","desc":"Every Saturday join us at The Depot for our weekly Super Sale! All items are slashed in price. Bring the whole family.","location":"The Depot at 100 Liberty Street"}}},"isManual":true,"widgetId":"fd3bcada-c82e-4ef8-8446-dece8025006a","section":"alt","category":"accent","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"fd3bcada-c82e-4ef8-8446-dece8025006a","widgetType":"CALENDAR","widgetPreset":"calendar1","order":1,"section":"alt","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Group","groupType":"Default","themeOverrides":{}});