(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-2',
          componentName:'CookieBanner',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"preset":"footer3","staticContent":{"YouTube":"YouTube Social Link","Facebook":"Facebook Social Link","acceptAndClose":"Accept & Close","Xing":"Xing Social Link","Houzz":"Houzz Social Link","Yelp":"Yelp Social Link","usingCookieTitle":"This website is using cookies.","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","cookiePolicy":"Cookie Policy","decline":"Decline","Pinterest":"Pinterest Social Link","LinkedIn":"LinkedIn Social Link","usingCookieMessage":"We use them to give you the best experience. If you continue using our website, we'll assume that you are happy to receive all cookies on this website."},"pages":[],"copyright":"Copyright © 2020 Clone Synthesis - All Rights Reserved.","poweredBy":"Powered by GoDaddy Website Builder","isAccountFree":true,"appName":"Website Builder","cookieBannerEnabled":false,"cookieBannerMessage":"{\"blocks\":[{\"key\":\"688aj\",\"text\":\"We use cookies to analyze website traffic and optimize your website experience. By accepting our use of cookies, your data will be aggregated with all other user data.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[{\"offset\":0,\"length\":0,\"key\":\"link\"}],\"data\":{}}],\"entityMap\":{\"link\":{\"type\":\"LINK\",\"mutability\":\"MUTABLE\",\"data\":{\"url\":\"\"}}}}","cookieBannerTitle":"This website uses cookies.","cookieBannerButtonLabel":"Accept","cookieBannerDeclineEnabled":false,"cookieBannerDeclineLabel":"Decline","isReseller":false,"market":"en-IN","rootDomain":"godaddy.com","planUpgradeLink":"https:\u002F\u002Fwww.godaddy.com\u002Fwebsites\u002Fwebsite-builder?isc=ISC#pricing","socialAccountsEnabled":true,"facebookProfile":"CloneSynthesis","twitterProfile":"CloneSynthesis","instagramProfile":"CloneSynthesis","pinterestProfile":null,"linkedinProfile":null,"youtubeProfile":null,"yelpProfile":null,"houzzProfile":null,"xingProfile":null,"editingCookieBanner":false,"id":"banner-f0f15b5e-09bc-4c74-bc41-8af7e0d8104f","widgetId":"f0f15b5e-09bc-4c74-bc41-8af7e0d8104f","section":"alt","category":"accent","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"f0f15b5e-09bc-4c74-bc41-8af7e0d8104f","widgetType":"FOOTER","widgetPreset":"footer3","order":2,"section":"alt","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Section","groupType":"Default","themeOverrides":{}});